---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cost-alert-rules
  namespace: monitoring
data:
  cost-alerts.yml: |
    groups:
    - name: cost_alerts
      interval: 60s
      rules:
      # Budget alerts
      - alert: BudgetExceeded90Percent
        expr: aws_budget_usage_percentage{cluster="node-fleet"} > 90
        for: 5m
        labels:
          severity: critical
          component: cost
        annotations:
          summary: "Monthly budget 90% exceeded"
          description: "Current budget usage is {{ $value }}%. You've used ${{ aws_budget_remaining_dollars }} of your monthly budget."
      
      - alert: BudgetExceeded75Percent
        expr: aws_budget_usage_percentage{cluster="node-fleet"} > 75
        for: 10m
        labels:
          severity: warning
          component: cost
        annotations:
          summary: "Monthly budget 75% exceeded"
          description: "Current budget usage is {{ $value }}%. Consider cost optimization."
      
      # Daily cost alerts
      - alert: DailyCostSpike
        expr: rate(aws_cluster_total_cost_daily{cluster="node-fleet"}[1h]) > 0.2
        for: 15m
        labels:
          severity: warning
          component: cost
        annotations:
          summary: "Daily cost increased rapidly"
          description: "Daily cost increased by more than 20% in the last hour."
      
      - alert: DailyCostThresholdExceeded
        expr: aws_cluster_total_cost_daily{cluster="node-fleet"} > 120
        for: 10m
        labels:
          severity: warning
          component: cost
        annotations:
          summary: "Daily cost exceeded $120"
          description: "Current daily cost is ${{ $value }}. Monthly projection: ${{ multiply $value 30 }}."
      
      # Hourly cost alerts
      - alert: HourlyCostTooHigh
        expr: aws_cluster_total_cost_hourly{cluster="node-fleet"} > 5
        for: 30m
        labels:
          severity: critical
          component: cost
        annotations:
          summary: "Hourly cost exceeds $5"
          description: "Current hourly cost is ${{ $value }}. This projects to ${{ multiply $value 720 }} per month."
      
      # Spot instance efficiency
      - alert: LowSpotUsage
        expr: aws_spot_savings_percentage{cluster="node-fleet"} < 20
        for: 1h
        labels:
          severity: info
          component: cost-optimization
        annotations:
          summary: "Spot instance usage below 20%"
          description: "Only {{ $value }}% cost savings from spot instances. Consider increasing spot ratio."
      
      - alert: NoSpotInstances
        expr: aws_cost_by_lifecycle{cluster="node-fleet",lifecycle="spot"} == 0
        for: 30m
        labels:
          severity: warning
          component: cost-optimization
        annotations:
          summary: "No spot instances running"
          description: "All instances are on-demand. You're missing ~65% cost savings."
      
      # Cost optimization opportunities
      - alert: HighOptimizationPotential
        expr: aws_potential_savings_hourly{cluster="node-fleet"} > 0.5
        for: 1h
        labels:
          severity: info
          component: cost-optimization
        annotations:
          summary: "Significant cost optimization opportunity"
          description: "Potential savings: ${{ $value }}/hr from {{ $labels.optimization_type }}."
      
      # Resource efficiency
      - alert: HighCostPerPod
        expr: aws_cost_per_pod{cluster="node-fleet"} > 0.05
        for: 30m
        labels:
          severity: warning
          component: cost-efficiency
        annotations:
          summary: "High cost per pod"
          description: "Cost per pod is ${{ $value }}/hr. Consider pod density optimization."
      
      - alert: ExpensiveInstanceType
        expr: aws_ec2_instance_cost_per_hour{cluster="node-fleet"} > 0.5
        labels:
          severity: info
          component: cost-efficiency
        annotations:
          summary: "Expensive instance detected"
          description: "Instance {{ $labels.instance_id }} ({{ $labels.instance_type }}) costs ${{ $value }}/hr."
      
      # Cost increase tracking
      - alert: RapidCostIncrease
        expr: abs(aws_cost_increase_rate{cluster="node-fleet"}) > 0.1
        for: 10m
        labels:
          severity: warning
          component: cost
        annotations:
          summary: "Rapid cost change detected"
          description: "Cost is changing at ${{ $value }}/hr/hr. Investigate scaling behavior."
      
      # Multi-AZ cost balance
      - alert: UnbalancedAZCosts
        expr: |
          (
            max(aws_cost_by_availability_zone{cluster="node-fleet"}) -
            min(aws_cost_by_availability_zone{cluster="node-fleet"})
          ) / avg(aws_cost_by_availability_zone{cluster="node-fleet"}) > 0.3
        for: 1h
        labels:
          severity: info
          component: cost-optimization
        annotations:
          summary: "Unbalanced cost across availability zones"
          description: "Cost variance between AZs exceeds 30%. Check instance distribution."
      
      # Budget forecast
      - alert: BudgetWillExceed
        expr: |
          (
            aws_cluster_total_cost_daily{cluster="node-fleet"} * 30
          ) > (aws_budget_remaining_dollars{cluster="node-fleet"} + (aws_cluster_total_cost_daily{cluster="node-fleet"} * day_of_month()))
        for: 1h
        labels:
          severity: warning
          component: cost
        annotations:
          summary: "Budget forecast: will exceed monthly limit"
          description: "At current rate, monthly cost will exceed budget. Consider scaling down."
