---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alerts
  namespace: monitoring
data:
  alerts.yml: |
    groups:
    - name: autoscaler_alerts
      interval: 30s
      rules:
      - alert: HighCPUUsage
        expr: avg(rate(node_cpu_seconds_total{mode!="idle"}[5m])) * 100 > 70
        for: 3m
        labels:
          severity: warning
          component: autoscaler
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is {{ $value }}% (threshold: 70%)"
      
      - alert: HighMemoryUsage
        expr: (1 - avg(node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 75
        for: 3m
        labels:
          severity: warning
          component: autoscaler
        annotations:
          summary: "High memory usage detected"
          description: "Memory usage is {{ $value }}% (threshold: 75%)"
      
      - alert: PendingPods
        expr: sum(kube_pod_status_phase{phase="Pending"}) > 0
        for: 3m
        labels:
          severity: warning
          component: autoscaler
        annotations:
          summary: "Pending pods detected"
          description: "{{ $value }} pods are in pending state"
      
      - alert: ScalingFailure
        expr: increase(autoscaler_scaling_failures_total[5m]) > 0
        labels:
          severity: critical
          component: autoscaler
        annotations:
          summary: "Autoscaler scaling failure"
          description: "Autoscaler failed to scale in the last 5 minutes"
      
      - alert: MaxNodesReached
        expr: count(kube_node_info) >= 10
        labels:
          severity: warning
          component: autoscaler
        annotations:
          summary: "Maximum node count reached"
          description: "Cluster has reached maximum capacity (10 nodes)"
      
      - alert: NodeNotReady
        expr: kube_node_status_condition{condition="Ready",status="false"} == 1
        for: 5m
        labels:
          severity: critical
          component: cluster
        annotations:
          summary: "Node not ready"
          description: "Node {{ $labels.node }} is not ready for more than 5 minutes"
      
      - alert: HighQueueDepth
        expr: app_queue_depth > 100
        for: 2m
        labels:
          severity: warning
          component: application
        annotations:
          summary: "High application queue depth"
          description: "Queue depth is {{ $value }} (threshold: 100)"
      
      - alert: HighAPILatency
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2
        for: 2m
        labels:
          severity: warning
          component: application
        annotations:
          summary: "High API latency (P95)"
          description: "P95 latency is {{ $value }}s (threshold: 2s)"
      
      - alert: HighErrorRate
        expr: (sum(rate(http_requests_total{status=~"5.."}[5m])) / sum(rate(http_requests_total[5m]))) * 100 > 5
        for: 2m
        labels:
          severity: critical
          component: application
        annotations:
          summary: "High error rate"
          description: "Error rate is {{ $value }}% (threshold: 5%)"
