apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus:9090
      basicAuth: true
      basicAuthUser: prometheus-admin
      basicAuthPassword: 'ED($is6xAkAXg4o&nCWhJ%M)&=7Xh8!['
      isDefault: true
    - name: CloudWatch
      type: cloudwatch
      access: proxy
      jsonData:
        authType: default
        defaultRegion: ap-southeast-1

